### ISSUE TITLE
Inaccurate information about the `let` keyword

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/fewpjs-js-fundamentals-variables#5]
In the **Identify When to Use `const`, `let`, and `var` for Declaring Variables** section, this lesson states that the `let` keyword "...will throw an error if you try to declare the same variable a second time". Further below, it states the same thing: "Using `let` instead of `var` will help you avoid silly errors like declaring the same variable at two different places within your code".

This is the example that the lesson provides:

> let pi = 3.14159;
> //=> undefined
>  
> let pi = "the ratio between a circle's circumference and diameter";
> //=> Uncaught SyntaxError: Identifier 'pi' has already been declared

There's just one little problem: That's not what happens! I tried out that example in the console in Chrome's DevTools and got this output instead:

```
let pi = 3.14159;
undefined
let pi = "the ratio between a circle's circumference and diameter";
undefined
pi;
"the ratio between a circle's circumference and diameter"
```

Contrary to what the lesson states, it actually IS possible to declare the same variable multiple times with the `let` keyword, without getting an Uncaught SyntaxError.

Thanks (as always) for looking into this!

--- Sdcrouse

**Comment by sylwiavargas** [comment]
Thank you! You right — Chrome's console allows for that. However, if you try this in your `node` console (in the terminal), you will get the error, just like when developing your app. I have edited the readme to better reflect what's happening and not lead anyone into confusion!

**Comment by Sdcrouse** [comment]
Awesome! Thanks for doing that, @sylwiavargas
